# Generated by Django 5.0.2 on 2024-03-03 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="reservations",
            field=models.ManyToManyField(
                related_name="reserved_books", to="book_management.books"
            ),
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="book_reservations",
                        to="book_management.books",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="member_reservations", to="book_management.members"
                    ),
                ),
            ],
        ),
    ]
