# Generated by Django 5.0.2 on 2024-03-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_management", "0002_members_reservations_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books", name="book_id", field=models.CharField(max_length=20),
        ),
    ]
