# Generated by Django 5.0.2 on 2024-03-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_management", "0003_alter_books_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="books_taken",
            field=models.ManyToManyField(
                default=[], related_name="member_books", to="book_management.books"
            ),
        ),
        migrations.AlterField(
            model_name="members",
            name="reservations",
            field=models.ManyToManyField(
                default=[], related_name="reserved_books", to="book_management.books"
            ),
        ),
    ]
