# Generated by Django 5.0.2 on 2024-03-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "book_management",
            "0004_alter_members_books_taken_alter_members_reservations",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="book_id",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="members", name="mem_id", field=models.CharField(unique=True),
        ),
    ]
