# Generated by Django 5.0.2 on 2024-03-03 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_management", "0005_alter_books_book_id_alter_members_mem_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="reservation", name="members",),
        migrations.AddField(
            model_name="reservation",
            name="members",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="member_reservations",
                to="book_management.members",
            ),
        ),
    ]
