# Generated by Django 5.0.2 on 2024-03-03 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_management", "0006_remove_reservation_members_reservation_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="book_reservations",
                to="book_management.books",
                unique=True,
            ),
        ),
    ]
