# Generated by Django 5.0.2 on 2024-03-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_management", "0007_alter_reservation_book"),
    ]

    operations = [
        migrations.RemoveField(model_name="reservation", name="members",),
        migrations.AddField(
            model_name="reservation",
            name="members",
            field=models.ManyToManyField(
                null=True,
                related_name="member_reservations",
                to="book_management.members",
            ),
        ),
    ]
