# Generated by Django 5.0.2 on 2024-03-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_management", "0008_remove_reservation_members_reservation_members"),
    ]

    operations = [
        migrations.RemoveField(model_name="members", name="reservations",),
    ]
